useGrid:  true
rows:     2
cols:     14
bandH:    70
peakTol:  60      

blur:     5
canny:    100

accOuter: 20
minROuter: 60
maxROuter: 130

accInner: 15
minRInner: 15
maxRInner: 50

minDist:  100
mergeTol: 50
