canny:            120
accumulator:       35
minRadius:         10
maxRadius:         55
blur:               5
clahe_clip:        2.0
minArea:          150
maxArea:        12000
circularity:       0.7
duplicateThresh:   12